# Changes here will be overwritten by Copier
_commit: v0.18.0
_src_path: gh:sarthakjariwala/django-vite-inertia
allauth: true
database: sqlite
docker_dev: false
docker_prod: true
frontend: vue
project_name: myproject
tailwind_css: true

